# This file is auto-synced from product-os/jellyfish-config/sync/.resinci-no-docker.yml
# and should only be edited there!

docker:
  publish: false
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/jellyfish-plugin-typeform_sut
      publish: false
      args:
        - BUILDKIT_INLINE_CACHE=1
      secrets:
        - id: npmrc
          src: .balena/secrets/npmrc.txt
        - id: integration_typeform_signature_key
          src: .balena/secrets/integration_typeform_signature_key.txt
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "14"
