version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    secrets:
      - integration_typeform_signature_key
    networks:
      - internal

secrets:
  integration_typeform_signature_key:
    file: ./.balena/secrets/integration_typeform_signature_key
